# Generated by Django 4.2.7 on 2024-02-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Shop admin", "Shop Admin"),
                            ("Product admin", "Product Admin"),
                            ("Category Admin", "Category Admin"),
                        ],
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ManyToManyField(to="users.role"),
        ),
    ]
