# Generated by Django 4.2.7 on 2024-02-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_role_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ManyToManyField(blank=True, to="users.role"),
        ),
    ]
