# Generated by Django 4.2.7 on 2024-03-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="users/"),
        ),
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.CharField(
                choices=[
                    ("Shop admin", "Shop Admin"),
                    ("Product admin", "Product Admin"),
                    ("Category admin", "Category Admin"),
                ],
                max_length=32,
            ),
        ),
    ]
