# Generated by Django 4.2.7 on 2024-02-26 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField()),
                ("parent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shop.category")),
            ],
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="product/")),
                ("is_main", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="shop/")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField()),
                ("amount", models.IntegerField(null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("active", models.BooleanField(default=True)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shop.category")),
                ("shop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shop.shop")),
            ],
        ),
    ]
