# Generated by Django 4.2.7 on 2024-02-26 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_category_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="active",
            new_name="is_active",
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="shop.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="product", to="shop.category"
            ),
        ),
    ]
