# Generated by Django 4.2.7 on 2024-02-26 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_rename_active_product_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="images",
            name="is_main",
        ),
        migrations.AddField(
            model_name="images",
            name="product",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="images", to="shop.product"
            ),
            preserve_default=False,
        ),
    ]
