# Generated by Django 4.2.7 on 2024-03-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_alter_product_category_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_ru",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="title_uz",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="description_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="title_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="title_ru",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="title_uz",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
